# Generated by Django 2.1.7 on 2019-09-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('start_date', models.DateField(verbose_name='Start Date')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationResearcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.Collaboration')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('pub_date', models.DateField(verbose_name='Publish Date')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('researcher', 'Researcher'), ('phd', 'PhD Student'), ('community', 'Star Community'), ('collab', 'Collaborator')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('web_page', models.CharField(max_length=500)),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('image', models.ImageField(blank=True, default='people_image/default-pic.jpg', upload_to='people_image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('date_added', models.DateField(verbose_name='Date Added')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('introduction', models.TextField(blank=True)),
                ('detail', models.FileField(blank=True, upload_to='software_detail')),
                ('pub_date', models.DateField(verbose_name='Publish Date')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Order of the author in software authors. Pictures will be shown in this order')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.People')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.Software')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='software',
            name='authors',
            field=models.ManyToManyField(through='main_api.SoftwareAuthors', to='main_api.People'),
        ),
        migrations.AddField(
            model_name='project',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.Research'),
        ),
        migrations.AddField(
            model_name='collaborationresearcher',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.People'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='researcher',
            field=models.ManyToManyField(through='main_api.CollaborationResearcher', to='main_api.People'),
        ),
    ]
