# Generated by Django 2.1.7 on 2019-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('invest', 'Investigator'), ('post', 'Post-doc'), ('phd', 'PhD'), ('former', 'Former')], max_length=6)),
                ('description', models.CharField(max_length=200)),
                ('web_page', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='people_image')),
            ],
        ),
    ]
