# Generated by Django 2.1.7 on 2019-03-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_people_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('introduction', models.TextField()),
                ('detail', models.FileField(upload_to='software_detail')),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, default='people_image/default-pic.jpg', upload_to='people_image'),
        ),
        migrations.AddField(
            model_name='software',
            name='authors',
            field=models.ManyToManyField(to='main_api.People'),
        ),
    ]
